// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/categories/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].put').default>>>>
    }
    '/api/categories/by-slug/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/by-slug/[slug].get').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/leads': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads.post').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/index.get').default>>>>
    }
    '/api/leads/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/[id].get').default>>>>
    }
    '/api/leads/with-products': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/leads/with-products').default>>>>
    }
    '/api/news/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/[id]').default>>>>
    }
    '/api/news': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news/index').default>>>>
    }
    '/api/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].put').default>>>>
    }
    '/api/products/by-slug/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/by-slug/[slug].get').default>>>>
    }
    '/api/products/filter-count': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/filter-count').default>>>>
    }
    '/api/products/filter': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/filter').default>>>>
    }
    '/api/products/filters-available': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/filters-available').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.post').default>>>>
    }
    '/api/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search.get').default>>>>
    }
    '/api/sources/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sources/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sources/[id].put').default>>>>
    }
    '/api/sources': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sources/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sources/index.post').default>>>>
    }
    '/api/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/upload.post').default>>>>
    }
    '/api/users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}